spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/PracticeDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    aws:
      region:
        static: ap-northeast-2
      secrets-manager:
        name: prod/AppDev/Postgresql
        max-cache-item-ttl: 4294967295